version: '3.6'
services:
  plantuml:
    image: 'plantuml/plantuml-server:jetty-v1.2021.1'
    ports:
      - '8080:8080'
    restart: always
  plantproxy:
    environment: 
      PLANTUML_SERVER: "plantproxy_plantuml_1"
      PLANTUML_SERVER_PORT: 8080
    build: .
    command: "start"
    depends_on:
      - plantuml
    ports:
      - '8081:8081'
    restart: always
